kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: >-
      JupyterLab minimal notebook image with R, IRKernel and RStudio.
    opendatahub.io/notebook-image-name: R Notebook
    opendatahub.io/notebook-image-order: '200'
    opendatahub.io/notebook-image-url: 'https://github.com/guimou/custom-notebooks/tree/main/r-notebook'
  name: odh-minimal-data-science-r-notebook
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"R","version":"4.0.5"},{"name":"RStudio","version":"2022.02.0-443"}]
        opendatahub.io/notebook-software: '[{"name":"BYO Notebook Image -
          R","version":"4.0.5"},{"name":"RStudio","version":"2022.02.0"},{"name":"Python","version":"3.9.10"}]'
      from:
        kind: DockerImage
        name: 'quay.io/guimou/odh-minimal-data-science-r-notebook:latest'
      referencePolicy:
        type: Source