kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
    name: christinas-rstudio-with-streamlit
    namespace: redhat-ods-applications
    labels:
      opendatahub.io/build_type: notebook_image 
      opendatahub.io/notebook-image: christinas-rstudio-streamlit
spec:
  source: 
    type: Git
    git:
      uri: https://github.com/christinaexyou/Custom-Notebook-Images-Best-Practices.git
    contextDir: r-notebook/container
  
  strategy:
    type: Docker
    dockerstrategy:
      dockerfilePath: Dockerfile
  output: 
    to:
      kind: ImageStreamTag
      name: christinas-rstudio-streamlit:v1