kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
        name: users-rstudio-streamlit
        namespace: redhat-ods-applications
        labels:
            opendatahub.io/build_type: notebook_image 
        opendatahub.io/notebook-image: users-rstudio-streamlit
    spec:
        source: 
            type: Git
            git:
            uri: https://github.com/rh-ai-services/Custom-Notebook-Images-Best-Practices.git
           contextDir: r-notebook/container
  
        strategy:
            type: Docker
            dockerstrategy:
            dockerfilePath: Dockerfile
        output: 
            to:
            kind: ImageStreamTag
            name: users-rstudio-streamlit:v1