kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: >-
      JupyterLab minimal notebook image with R, IRKernel and RStudio.
    opendatahub.io/notebook-image-name: users rstudio streamlit
    opendatahub.io/notebook-image-order: '200'
    opendatahub.io/notebook-image-url: 'https://github.com/rh-ai-services/Custom-Notebook-Images-Best-Practices/tree/main/r-notebook'
  name: users-rstudio-streamlit 
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
    app.kubernetes.io/created-by: byon 
spec:
  lookupPolicy:
    local: true
  tags:
    - name: v1
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"R","version":"4.0.5"},{"name":"RStudio","version":"2022.02.0-443"}]
        opendatahub.io/notebook-software: '[{"name":"BYO Notebook Image -
          R","version":"4.0.5"},{"name":"RStudio","version":"2022.02.0"},{"name":"Python","version":"3.9.10"}, 
          {"name": "Streamlit", "version":"1.11.1"}]'
      referencePolicy: 
         type: Local
